### ISSUE TITLE
Clicking outside modal dialog

### ISSUE THREAD

**Issue by jrvidotti** [thbst16/BlazorCrud#4]
Expected behavior is closing dialog, but app don't closes and any other buttons stops working.

**Comment by thbst16** [comment]
This is a nasty one. Was able to reproduce exactly as described. I need to go back and see if this is an issue with the underlying modal control behavior in BlazorStrap or something I need to handle.

@jrvidotti - You don't happen to know whether this is an underlying issue with the BlazorStrap control, do you?

**Comment by jrvidotti** [comment]
Very nice! I am a beginner with Blazor and your project helped me a lot. Thank you!
