### ISSUE TITLE
1 bug with Fluentvalidation 

### ISSUE THREAD

**Issue by icedenis** [thbst16/BlazorCrud#7]
1) go to Claims 
2) add new Claim
3) Submit without adding any data to get the validation error msgs
4) Try to go with the arrows to Amount of 30 or more.
5) Thats it
 With the FluentValidator there is alway this bug with out of memory. but the other  DataAnnotationsValidator  there is no such Problem .

**Comment by thbst16** [comment]
Thank you. This is absolutely a bug. I do believe it's tied to the fluent validation upgrade that I did last week as a part of the overall solution NuGet package update. I'll need to rollback to the version prior to the upgrade and see if the issue was there prior to the fluent validation upgrade. If you could do so before I do, please let me know the results.

**Comment by icedenis** [comment]
On the old Version the bug was still there. I try to fix it as well,if i can reach any solution will post it here and thx a lot

**Comment by icedenis** [comment]
`using FluentValidation;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using System;

namespace BlazorCrud.Shared.Models
{
    public class FluentValidator<TValidator> : ComponentBase where TValidator : IValidator, new()

    {

        private readonly static char[] separators = new[] { '.', '[' };

        private TValidator validator;



        [CascadingParameter] private EditContext EditContext { get; set; }



        protected override void OnInitialized()

        {

            validator = new TValidator();

            var messages = new ValidationMessageStore(EditContext);



            // Revalidate when any field changes, or if the entire form requests validation

            // (e.g., on submit)



            EditContext.OnFieldChanged += (sender, eventArgs)

                => ValidateModel((EditContext)sender, messages);



            EditContext.OnValidationRequested += (sender, eventArgs)

                => ValidateModel((EditContext)sender, messages);

        }



        private void ValidateModel(EditContext editContext, ValidationMessageStore messages)

        {

            var context = new ValidationContext<object>(editContext.Model);
            var validationResult = validator.Validate(context);

            messages.Clear();

            foreach (var error in validationResult.Errors)

            {

                var fieldIdentifier = ToFieldIdentifier(editContext, error.PropertyName);

                messages.Add(fieldIdentifier, error.ErrorMessage);

            }

            editContext.NotifyValidationStateChanged();

        }



        private static FieldIdentifier ToFieldIdentifier(EditContext editContext, string propertyPath)

        {

            // This method parses property paths like 'SomeProp.MyCollection[123].ChildProp'

            // and returns a FieldIdentifier which is an (instance, propName) pair. For example,

            // it would return the pair (SomeProp.MyCollection[123], "ChildProp"). It traverses

            // as far into the propertyPath as it can go until it finds any null instance.



            var obj = editContext.Model;



            while (true)

            {

                var nextTokenEnd = propertyPath.IndexOfAny(separators);

                if (nextTokenEnd < 0)

                {

                    return new FieldIdentifier(obj, propertyPath);

                }



                var nextToken = propertyPath.Substring(0, nextTokenEnd);

                propertyPath = propertyPath.Substring(nextTokenEnd + 1);



                object newObj;

                if (nextToken.EndsWith("]"))

                {

                    // It's an indexer

                    // This code assumes C# conventions (one indexer named Item with one param)

                    nextToken = nextToken.Substring(0, nextToken.Length - 1);

                    var prop = obj.GetType().GetProperty("Item");

                    var indexerType = prop.GetIndexParameters()[0].ParameterType;

                    var indexerValue = Convert.ChangeType(nextToken, indexerType);

                    newObj = prop.GetValue(obj, new object[] { indexerValue });

                }

                else

                {

                    // It's a regular property

                    var prop = obj.GetType().GetProperty(nextToken);

                    if (prop == null)

                    {

                        throw new InvalidOperationException($"Could not find property named {nextToken} on object of type {obj.GetType().FullName}.");

                    }

                    newObj = prop.GetValue(obj);

                }



                if (newObj == null)

                {

                    // This is as far as we can go

                    return new FieldIdentifier(obj, nextToken);

                }



                obj = newObj;

            }

        }

    }
}
`
### This code looks like fixed the bug i dont know where was it
